# 数据集配置
MovingMNIST:
  data_path: "Data/MovingMNIST/train-images-idx3-ubyte.gz"
  input_frames: 10
  output_frames: 10
  use_augment: False
  batch_size_train: 16
  batch_size_valid: 4
  num_workers: 4

TaxiBJ:
  data_path: "Data/TaxiBJ/taxibj.npz"
  use_augment: False
  batch_size_train: 32
  batch_size_valid: 4
  num_workers: 0

SEVIR:
  train_data_path: Data\SEVIR\SEVIR_VIL_STORMEVENTS_train.h5
  test_data_path: Data\SEVIR\SEVIR_VIL_STORMEVENTS_test.h5
  batch_size_train: 16
  batch_size_valid: 4
  valid_ratio: 0.1
  num_workers: 0