# 模型参数
model:
  input_shape: [7, 1, 128, 128]
  # 可选的translator_type有"IncepU"、"gSTA"和"TAU"，分别对应SimVP的V1、V2和V3版本
  translator_type: IncepU
  hid_channels_S: 64
  hid_channels_T: 256
  layers_S: 2
  layers_T: 4
  # IncepU所需参数
  inception_kernels: [3, 5, 7, 11]
  groups: 8
  # gSTA和TAU所需参数
  kernel_size: 21
  mlp_ratio: 4.0
  drop_ratio: 0
  drop_path_prob: 0.1

# 训练参数
epochs: 150
lr: 0.001
max_lr: 0.01
optimizer: Adam
scheduler: OneCycleLR
patience: 15
seed: 42
resume_from: 

# 测试参数
model_path: 
save_interval: 10