# 模型参数
model:
  in_channels: 1
  out_channels: 1
  in_frames: 7
  out_frames: 6
  bilinear: true

# 训练参数
epochs: 200
lr: 0.001
optimizer: Adam
scheduler: ReduceLROnPlateau
patience: 20
seed: 42
resume_from: 

# 测试参数
model_path: Output\Checkpoint\SEVIR\UNet_epoch=79_loss=0.0046.pt
save_interval: 10